### ISSUE TITLE
Access denied for command ...

### ISSUE THREAD

**Issue by Mryococo91** [NexusCoreDev/Core#7]
I have created my server with your framework and I have errors in the console of my server.

Access denied for command ensure => when I launch my server
and
Access denied for command add_principal => when I create my character
![NexCore access denied](https://user-images.githubusercontent.com/40495086/114472623-958cf080-9bc0-11eb-95e3-52986d8393b2.png)

**Comment by Mryococo91** [comment]
I tried to join your discord but the discord was empty, probably a bug of my conection. your discord is on which part of the continent?

**Comment by AlexMartSch** [comment]
> I have created my server with your framework and I have errors in the console of my server.
> 
> Access denied for command ensure => when I launch my server
> and
> Access denied for command add_principal => when I create my character
> ![NexCore access denied](https://user-images.githubusercontent.com/40495086/114472623-958cf080-9bc0-11eb-95e3-52986d8393b2.png)

Hello @Mryococo91, you can set this into your server.cfg

```
add_ace resource.nex_core command.add_ace allow
add_ace resource.nex_core command.remove_principal allow
add_ace resource.nex_core command.add_principal allow
add_ace resource.nex_core command.remove_ace allow
add_ace resource.nex_core command.list_aces allow
add_ace resource.nex_core command.list_principals allow
add_ace resource.nex_core command.remove_aces_for_object allow

add_ace resource.nex_core command.ensure allow
add_ace resource.nex_core command.start allow
add_ace resource.nex_core command.stop allow
```
